=== tgextreme/NetBeansProyects/trabajo1/src/LM/parte1.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/parte1.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE equipo SYSTEM "parte1.dtd">

    <equipo>
    ...
    </equipo>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT equipo (temporada)*>
<!ATTLIST equipo
    aforo CDATA #IMPLIED
    estadio CDATA #IMPLIED
    fundado CDATA #IMPLIED
    nombre CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT temporada (JugadorDatos)*>
<!ATTLIST temporada
    MesFinal CDATA #IMPLIED
    DiaFinal CDATA #IMPLIED
    MesInicio CDATA #IMPLIED
    DiaInicio CDATA #IMPLIED
    CualEs CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT JugadorDatos (situacionLaboral|CaracteristicasFisicas)*>
<!ATTLIST JugadorDatos
    proviene CDATA #IMPLIED
    alias CDATA #IMPLIED
    nombre CDATA #IMPLIED
    ID CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CaracteristicasFisicas EMPTY>
<!ATTLIST CaracteristicasFisicas
    LugarNacimiento CDATA #IMPLIED
    FechaNacimiento CDATA #IMPLIED
    peso CDATA #IMPLIED
    altura CDATA #IMPLIED
    dorsal CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT situacionLaboral (EnElcampoEstaTemporada|EnElCampoEstaTemporada)*>
<!ATTLIST situacionLaboral
    ExperienciaFuncion CDATA #IMPLIED
    ExperienciaTiempo CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT EnElCampoEstaTemporada EMPTY>
<!ATTLIST EnElCampoEstaTemporada
    TarjetaRoja CDATA #IMPLIED
    TarjetaAmarilla CDATA #IMPLIED
    goles CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT EnElcampoEstaTemporada EMPTY>
<!ATTLIST EnElcampoEstaTemporada
    TarjetaRoja CDATA #IMPLIED
    TarjetaAmarilla CDATA #IMPLIED
    goles CDATA #IMPLIED
  >

=== tgextreme/NetBeansProyects/trabajo1/src/LM/parte1.xml
<?xml version="1.0" encoding="utf-8"
     standalone="no"?>
<!DOCTYPE equipo SYSTEM "parte1.dtd">

    <equipo nombre="UD Almeria" fundado="1989" 
            estadio="Estadio de los Juegos Mediterraneos" 
            aforo="15200 personas">

        
    <temporada CualEs="13/14" DiaInicio="19" MesInicio="8" DiaFinal="18" MesFinal="5">
        <JugadorDatos ID="1" nombre = "Rodrigo Díaz Lozano" alias ="Rodri" proviene="FC Barcelona" >
            <CaracteristicasFisicas dorsal="10" altura="1.78m" peso="64 kg" FechaNacimiento="6/6/1990" LugarNacimiento="Soria"/>
            <situacionLaboral ExperienciaTiempo="7 meses 'esta temporada'" ExperienciaFuncion="titular">		
                <EnElCampoEstaTemporada goles="4" TarjetaAmarilla="1" TarjetaRoja="0"/>
            </situacionLaboral>
			
        </JugadorDatos>

       
            <JugadorDatos ID="2" nombre="Jesús Fernández Sáez" alias="Suso" proviene="Liverpool">
                <CaracteristicasFisicas dorsal="17" altura="1.76m" peso="70 kg" FechaNacimiento="19/11/1990" LugarNacimiento="Cadiz"/>
                <situacionLaboral ExperienciaTiempo="7 partidos" ExperienciaFuncion="6 de titular, 1 de suplente">		
                    <EnElcampoEstaTemporada 
                         goles="1" TarjetaAmarilla="3" TarjetaRoja="0"/>
                </situacionLaboral>
        </JugadorDatos>
    </temporada>
		
    
	


    </equipo>
